baseURL = "https://thefajarmalik.com"
languageCode = "en-us"
title = "Fajar Malik"
theme = "careercanvas"

[params]
name = "Fajar Malik"
tagline = "Consultant. Developer. Hacker."
location = "Helsinki, Finland"
email = "mrfajarmalik@gmail.com"
profile_image = "/images/fajar-profile.png"
description = "I am a cyber security, IT consulting, and software development specialist with a Nordic perspective, holding Master's degrees from Aalto in Finland and NTNU in Norway."
author = "Fajar Malik"
og_image = "/images/og-image.jpg"

# hero_description = "I am a cyber security, IT consulting, and software development specialist with a Nordic perspective, holding Master's degrees in <b>Security & Cloud</b> from Aalto University&nbsp;ðŸ‡«ðŸ‡® and NTNU&nbsp;ðŸ‡³ðŸ‡´<br>I want to help organizations build secure, practical systems with a structured & detail-oriented approach."
hero_description = "I am a cyber security, IT consulting, and software development specialist with a Nordic perspective, holding Master's degrees in Security & Cloud from Aalto University&nbsp;ðŸ‡«ðŸ‡® and NTNU&nbsp;ðŸ‡³ðŸ‡´"
hero_location = "Helsinki, Finland ðŸ‡«ðŸ‡®"

linkedin_url = "https://www.linkedin.com/in/thefajarmalik"
linkedin_text = "linkedin.com/in/thefajarmalik"
github_url = "https://github.com/thefajarmalik"
github_text = "github.com/thefajarmalik"

copyright = "Â© 2025 | Fajar Malik"

collab_tags = ["Cyber Security", "Software Development", "IT Consulting"]

# Technical skills configuration
[params.technical_skills]
# FontAwesome brand icons (for special icons like Python, JS, etc.)
brand_icons = [
  "python",
  "js",
  "html5",
  "css3-alt",
  "linux",
  "docker",
  "github",
  "gitlab",
  "golang",
  "google",
  "android",
  "react",
  "git",
  "node-js",
  "java",
  "cuttlefish"
]

[[params.social]]
icon = "linkedin-in"
url = "https://www.linkedin.com/in/thefajarmalik"

[[params.social]]
icon = "github"
url = "https://github.com/thefajarmalik"

sectionPagesMenu = 'main'

[[menu.main]]
name = "Featured"
url = "/#featured"
weight = 2

[[menu.main]]
name = "About"
url = "/#about"
weight = 3

[[menu.main]]
name = "Technical Skills"
url = "/#technical"
weight = 4

[[menu.main]]
name = "Experience"
url = "/#experience"
weight = 5

[[menu.main]]
name = "Contact"
url = "/#contact"
weight = 6

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 7

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 60

[taxonomies]
tag = "tags"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"

[server]
[[server.headers]]
for = "/**/*.css"
[server.headers.values]
Content-Type = "text/css"
